---
- name: Actvities on openstack platform
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - "{{ playbook_dir }}/vars/var.yml"
  - "{{ playbook_dir }}/vars/default.yml"
  tasks:
    - name: Storing auth credentials in variables of openstack platform
      set_fact:
        os_auth_url: "{{ credentials.OS_AUTH_URL }}"
        os_username: "{{ credentials.OS_USERNAME }}"
        os_password: "{{ credentials.OS_PASSWORD }}"
        os_project_name: "{{ credentials.OS_PROJECT_NAME }}"

    - name: Network activities 
      ansible.builtin.import_role: 
        name: network

    - name: Volume activities
      ansible.builtin.import_role: 
        name: volume

    - name: Instance activities
      ansible.builtin.import_role: 
        name: instance

    - name: Backup activities
      ansible.builtin.import_role: 
        name: backup