---
- name: Actvities on openstack platform
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - "{{ playbook_dir }}/vars/var.yml"
  - "{{ playbook_dir }}/vars/defaults.yml"
  tasks:
    - name: Instance actions 
      import_role: instance

    - name: Storage actions 
      import_role: volume

    - name: Backup activities
      import_role: backup