---
- name: Actvities on openstack platform
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - "{{ playbook_dir }}/vars/var.yml"
  - "{{ playbook_dir }}/vars/default.yml"
  tasks:
    - name: Network activities 
      ansible.builtin.import_role: 
        name: network

    - name: Volume activities
      ansible.builtin.import_role: 
        name: volume

    - name: Instance activities
      ansible.builtin.import_role: 
        name: instance

    - name: Backup activities
      ansible.builtin.import_role: 
        name: backup