---
roles:
  - name: instance role
    src: https://github.com/Venky0827/instance.git
    version: main
    scm: git
  - name: volume role
    src: https://github.com/Venky0827/volume.git
    version: main
    scm: git
  - name: backup role
    src: https://github.com/Venky0827/backup.git
    version: main
    scm: git